apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: capstone-project1-pod-user
spec:
  # request: $(cat capstone-project1-pod-user.csr | base64 | tr -d '\n')
  request: __CSR___
  usages:
  - digital signature
  - key encipherment
  - server auth
  signerName: kubernetes.io/kubelet-serving
